replicaCount: 2

image:
  repository: fabriziosalmi/zion
  pullPolicy: IfNotPresent
  tag: "v0.1.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: LoadBalancer
  portHttp: 80
  portHttps: 443

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

# Zion Configuration
config:
  listen_http: "0.0.0.0:80"
  listen_https: "0.0.0.0:443"
  # You can mount a Secret and define certificates paths here
  # cert_path: "/etc/ssl/zion/tls.crt"
  # key_path: "/etc/ssl/zion/tls.key"
  upstreams: {}
  routes: []
