apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zion.fullname" . }}
  labels:
    {{- include "zion.labels" . | nindent 4 }}
data:
  zion.toml: |
    [server]
    listen_http = {{ .Values.config.listen_http | quote }}
    listen_https = {{ .Values.config.listen_https | quote }}

    [upstreams]
    {{- range $k, $v := .Values.config.upstreams }}
    {{ $k }} = {{ $v | quote }}
    {{- end }}

    {{- range .Values.config.routes }}
    [[route]]
    path = {{ .path | quote }}
    upstream = {{ .upstream | quote }}
    {{- if .waf }}
    waf = true
    {{- end }}
    {{- end }}
