apiVersion: v1
kind: Service
metadata:
  name: {{ include "zion.fullname" . }}
  labels:
    {{- include "zion.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.portHttp }}
      targetPort: http
      protocol: TCP
    - name: https
      port: {{ .Values.service.portHttps }}
      targetPort: https
      protocol: TCP
    - name: quic
      port: {{ .Values.service.portHttps }}
      targetPort: quic
      protocol: UDP
  selector:
    {{- include "zion.selectorLabels" . | nindent 4 }}
