//! Baked-in Italian CIDR ranges for sovereign edge classification.
//!
//! AUTO-GENERATED by scripts/generate_sovereign_data.py
//! DO NOT EDIT MANUALLY — changes will be overwritten by CI.
//!
//! Sources: RIPE NCC delegated stats + IPtoASN (iptoasn.com), v4 + v6.
//! Snapshot date: 2026-10-06 (curated-ASN holders validated against RIPEstat as-overview on this date — see the generator).
//!
//! The table follows the weekly snapshots with a delay: a run of addresses enters a
//! class after 2 snapshots that agree, and leaves or changes class after 3. What is
//! observed and not yet published is in `data_ita.pending.json`, next to this file.

use super::{CidrEntry, CidrEntry6, IpClass};

/// Sorted by start IP (ascending), non-overlapping.
#[rustfmt::skip]
pub static RANGES: &[CidrEntry] = &[
    // ── RESIDENTIAL ISPs ──
    cr(0x02101100, 0x021011FF, IpClass::ResidentialIta),
    cr(0x0213B300, 0x0213B3FF, IpClass::ResidentialIta),
    cr(0x02200000, 0x02256EFF, IpClass::ResidentialIta),
    cr(0x02257000, 0x022FFFFF, IpClass::ResidentialIta),
    cr(0x02700000, 0x0277FFFF, IpClass::ResidentialIta),
    cr(0x029C0000, 0x029FFFFF, IpClass::ResidentialIta),
    cr(0x02C00000, 0x02C7FFFF, IpClass::ResidentialIta),
    cr(0x02E00000, 0x02EFFFFF, IpClass::ResidentialIta),
    cr(0x05012C00, 0x05012CFF, IpClass::ResidentialIta),
    cr(0x050B7000, 0x050B7FFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0x05380800, 0x05380FFF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0x054D4000, 0x054D7FFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0x05537800, 0x05537FFF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0x05580000, 0x0563FFFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0x05989000, 0x059890FF, IpClass::DatacenterIta),
    cr(0x05989500, 0x059895FF, IpClass::DatacenterIta),
    cr(0x05989A00, 0x05989AFF, IpClass::DatacenterIta),
    cr(0x05989C00, 0x05989CFF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0x0598F000, 0x0598F7FF, IpClass::ResidentialIta),
    cr(0x059D6000, 0x059D7FFF, IpClass::ResidentialIta),
    cr(0x05A80000, 0x05ABFFFF, IpClass::ResidentialIta),
    cr(0x05B38000, 0x05B3BFFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0x05B6F000, 0x05B6F3FF, IpClass::DatacenterIta),
    cr(0x05B76F00, 0x05B76FFF, IpClass::DatacenterIta),
    cr(0x05F98000, 0x05F99FFF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0x05FC5400, 0x05FC55FF, IpClass::ResidentialIta),
    cr(0x173DCC00, 0x173DCCFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0x1F065000, 0x1F065FFF, IpClass::DatacenterIta),
    cr(0x1F079000, 0x1F079FFF, IpClass::DatacenterIta),
    cr(0x1F0B2000, 0x1F0B27FF, IpClass::DatacenterIta),
    cr(0x1F0E8000, 0x1F0E8FFF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0x1F1A0000, 0x1F1B3FFF, IpClass::ResidentialIta),
    cr(0x1F1B6000, 0x1F1B6FFF, IpClass::ResidentialIta),
    cr(0x1F1B8000, 0x1F1BFFFF, IpClass::ResidentialIta),
    cr(0x1F83F000, 0x1F83F7FF, IpClass::ResidentialIta),
    cr(0x1F9C0000, 0x1F9FFFFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0x1FAA2A00, 0x1FAA2BFF, IpClass::DatacenterIta),
    cr(0x1FABD200, 0x1FABD2FF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0x1FBE0000, 0x1FBFFFFF, IpClass::ResidentialIta),
    cr(0x1FC20000, 0x1FC7FFFF, IpClass::ResidentialIta),
    cr(0x25205000, 0x252057FF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0x254DA000, 0x254DA7FF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0x2563F000, 0x2563F0FF, IpClass::ResidentialIta),
    cr(0x25640000, 0x2567FFFF, IpClass::ResidentialIta),
    cr(0x25740000, 0x2577FFFF, IpClass::ResidentialIta),
    cr(0x25998700, 0x259987FF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0x259CF400, 0x259CF4FF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0x259F0000, 0x259FFFFF, IpClass::ResidentialIta),
    cr(0x25B00000, 0x25B7FFFF, IpClass::ResidentialIta),
    cr(0x25BAC000, 0x25BAFFFF, IpClass::ResidentialIta),
    cr(0x25CD8000, 0x25CFFFFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0x2D0B7400, 0x2D0B77FF, IpClass::DatacenterIta),
    cr(0x2D0D5800, 0x2D0D5BFF, IpClass::DatacenterIta),
    cr(0x2D0D7800, 0x2D0D7BFF, IpClass::DatacenterIta),
    cr(0x2D0EB800, 0x2D0EBBFF, IpClass::DatacenterIta),
    cr(0x2D425200, 0x2D4253FF, IpClass::DatacenterIta),
    cr(0x2D50AC00, 0x2D50ADFF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0x2D52E400, 0x2D52E7FF, IpClass::ResidentialIta),
    cr(0x2D5A7C00, 0x2D5A7CFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0x2D5AE800, 0x2D5AEBFF, IpClass::DatacenterIta),
    cr(0x2D5D2400, 0x2D5D27FF, IpClass::DatacenterIta),
    cr(0x2D83EE00, 0x2D83EFFF, IpClass::DatacenterIta),
    cr(0x2D8AC800, 0x2D8ACBFF, IpClass::DatacenterIta),
    cr(0x2D9C3C00, 0x2D9C3FFF, IpClass::DatacenterIta),
    cr(0x2E1F6800, 0x2E1F6FFF, IpClass::DatacenterIta),
    cr(0x2E250000, 0x2E251FFF, IpClass::DatacenterIta),
    cr(0x2EE55000, 0x2EE55FFF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0x2F350000, 0x2F35FFFF, IpClass::ResidentialIta),
    cr(0x31EC0000, 0x31EC3FFF, IpClass::ResidentialIta),
    cr(0x3E120000, 0x3E13FFFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0x3E55C000, 0x3E55FFFF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0x3E560000, 0x3E5619FF, IpClass::ResidentialIta),
    cr(0x3E561B00, 0x3E5673FF, IpClass::ResidentialIta),
    cr(0x3E567500, 0x3E56FFFF, IpClass::ResidentialIta),
    cr(0x3E620000, 0x3E62FFFF, IpClass::ResidentialIta),
    cr(0x3E645A00, 0x3E645AFF, IpClass::ResidentialIta),
    cr(0x3E654000, 0x3E657FFF, IpClass::ResidentialIta),
    cr(0x3E6E0000, 0x3E6EFFFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0x3E7B0000, 0x3E7BFFFF, IpClass::DatacenterIta),
    cr(0x3E958000, 0x3E95FFFF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0x3EB10000, 0x3EB10FFF, IpClass::ResidentialIta),
    cr(0x3EB66700, 0x3EB667FF, IpClass::ResidentialIta),
    cr(0x3ED30000, 0x3ED3FFFF, IpClass::ResidentialIta),
    cr(0x407EFA00, 0x407EFAFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0x42478000, 0x42478FFF, IpClass::DatacenterIta),
    cr(0x4247B000, 0x4247B7FF, IpClass::DatacenterIta),
    cr(0x4A7AEF00, 0x4A7AEFFF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0x4D200000, 0x4D207FFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0x4D51E000, 0x4D51EFFF, IpClass::DatacenterIta),
    cr(0x4DDF0400, 0x4DDF07FF, IpClass::DatacenterIta),
    cr(0x4E040000, 0x4E07FFFF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0x4E860000, 0x4E867FFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0x4E8A2000, 0x4E8A23FF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0x4F000000, 0x4F2FFFFF, IpClass::ResidentialIta),
    cr(0x4F310000, 0x4F3FFFFF, IpClass::ResidentialIta),
    cr(0x50100000, 0x5017FFFF, IpClass::ResidentialIta),
    cr(0x50434200, 0x504342FF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0x50467400, 0x504677FF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0x5047EA00, 0x5047EAFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0x5049E000, 0x5049E7FF, IpClass::DatacenterIta),
    cr(0x50585000, 0x50585FFF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0x50B40000, 0x50B4FFFF, IpClass::ResidentialIta),
    cr(0x50B70000, 0x50B7FFFF, IpClass::ResidentialIta),
    cr(0x50CC0000, 0x50CFFFFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0x50D30000, 0x50D3BFFF, IpClass::DatacenterIta),
    cr(0x50D3E000, 0x50D3EFFF, IpClass::DatacenterIta),
    cr(0x511B4A00, 0x511B4AFF, IpClass::DatacenterIta),
    cr(0x511DB000, 0x511DB3FF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0x51480000, 0x514AEDFF, IpClass::ResidentialIta),
    cr(0x514AF000, 0x514AFBFF, IpClass::ResidentialIta),
    cr(0x514AFD00, 0x514BFFFF, IpClass::ResidentialIta),
    cr(0x51510000, 0x5151FFFF, IpClass::ResidentialIta),
    cr(0x51700000, 0x51736DFF, IpClass::ResidentialIta),
    cr(0x51736F00, 0x517371FF, IpClass::ResidentialIta),
    cr(0x51737400, 0x517375FF, IpClass::ResidentialIta),
    cr(0x51737800, 0x5175BAFF, IpClass::ResidentialIta),
    cr(0x5175BD00, 0x51777FFF, IpClass::ResidentialIta),
    cr(0x51778200, 0x517786FF, IpClass::ResidentialIta),
    cr(0x51778800, 0x517788FF, IpClass::ResidentialIta),
    cr(0x51778A00, 0x517B63FF, IpClass::ResidentialIta),
    cr(0x517B6600, 0x517BB3FF, IpClass::ResidentialIta),
    cr(0x517BB800, 0x517BB8FF, IpClass::ResidentialIta),
    cr(0x517BBB00, 0x517BBBFF, IpClass::ResidentialIta),
    cr(0x517BBE00, 0x517C74FF, IpClass::ResidentialIta),
    cr(0x517C7A00, 0x517C7BFF, IpClass::ResidentialIta),
    cr(0x517C7E00, 0x517D77FF, IpClass::ResidentialIta),
    cr(0x517D7A00, 0x517D7BFF, IpClass::ResidentialIta),
    cr(0x517D7D00, 0x517D7DFF, IpClass::ResidentialIta),
    cr(0x517D7F00, 0x517D7FFF, IpClass::ResidentialIta),
    cr(0x517D8100, 0x517D84FF, IpClass::ResidentialIta),
    cr(0x517D8700, 0x517D8AFF, IpClass::ResidentialIta),
    cr(0x517D8C00, 0x517D8CFF, IpClass::ResidentialIta),
    cr(0x517D8E00, 0x517E3FFF, IpClass::ResidentialIta),
    cr(0x517E6000, 0x517E7FFF, IpClass::ResidentialIta),
    cr(0x517E9000, 0x517E90FF, IpClass::ResidentialIta),
    cr(0x517E9200, 0x517E9FFF, IpClass::ResidentialIta),
    cr(0x517EE000, 0x517EFFFF, IpClass::ResidentialIta),
    cr(0x51AE0000, 0x51AE3FFF, IpClass::ResidentialIta),
    cr(0x51D00000, 0x51D07FFF, IpClass::ResidentialIta),
    cr(0x52300000, 0x5230FFFF, IpClass::ResidentialIta),
    cr(0x52350000, 0x5235BAFF, IpClass::ResidentialIta),
    cr(0x5235BC00, 0x5236FFFF, IpClass::ResidentialIta),
    cr(0x52390000, 0x5239CFFF, IpClass::ResidentialIta),
    cr(0x5239D800, 0x523BFFFF, IpClass::ResidentialIta),
    cr(0x523E0000, 0x523FFFFF, IpClass::ResidentialIta),
    cr(0x52540000, 0x5255AFFF, IpClass::ResidentialIta),
    cr(0x5255B100, 0x5255FFFF, IpClass::ResidentialIta),
    cr(0x52580000, 0x525BFFFF, IpClass::ResidentialIta),
    cr(0x52680000, 0x526BFFFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0x52A32000, 0x52A323FF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0x52B80000, 0x52BFFFFF, IpClass::ResidentialIta),
    cr(0x53670000, 0x53677FFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0x53886A00, 0x53886BFF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0x53E04000, 0x53E04FFF, IpClass::ResidentialIta),
    cr(0x53E08000, 0x53E1FFFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0x53E50800, 0x53E50BFF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0x54214000, 0x5421BFFF, IpClass::ResidentialIta),
    // ── GOVERNMENT / INSTITUTIONAL ──
    cr(0x54263000, 0x54263FFF, IpClass::GovIta),
    // ── RESIDENTIAL ISPs ──
    cr(0x5435B800, 0x5435B8FF, IpClass::ResidentialIta),
    cr(0x54DC0000, 0x54DDFFFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0x54EA6400, 0x54EA67FF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0x55120000, 0x5512FFFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0x55140000, 0x5514FFFF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0x55200000, 0x552102FF, IpClass::ResidentialIta),
    cr(0x55210400, 0x55250FFF, IpClass::ResidentialIta),
    cr(0x55251200, 0x552DF9FF, IpClass::ResidentialIta),
    cr(0x552DFB00, 0x552FFFFF, IpClass::ResidentialIta),
    cr(0x55769100, 0x557691FF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0x559F7300, 0x559F73FF, IpClass::DatacenterIta),
    cr(0x55D04C00, 0x55D04FFF, IpClass::DatacenterIta),
    cr(0x55EB8000, 0x55EB9DFF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0x57000000, 0x571FFFFF, IpClass::ResidentialIta),
    cr(0x58200000, 0x58211AFF, IpClass::ResidentialIta),
    cr(0x58211C00, 0x582C3BFF, IpClass::ResidentialIta),
    cr(0x582C3D00, 0x582C3EFF, IpClass::ResidentialIta),
    cr(0x582C4000, 0x583FFFFF, IpClass::ResidentialIta),
    cr(0x58930000, 0x58937FFF, IpClass::ResidentialIta),
    cr(0x58958000, 0x5895FFFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0x5915C000, 0x5915DFFF, IpClass::DatacenterIta),
    cr(0x5924D000, 0x5924D3FF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0x5927C800, 0x5927C8FF, IpClass::ResidentialIta),
    cr(0x592BC000, 0x592BC0FF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0x592DE400, 0x592DE4FF, IpClass::DatacenterIta),
    cr(0x592E4000, 0x592E4FFF, IpClass::DatacenterIta),
    cr(0x592E6800, 0x592E6FFF, IpClass::DatacenterIta),
    cr(0x592EC000, 0x592EC7FF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0x59600000, 0x5961FFFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0x59760000, 0x5977FFFF, IpClass::DatacenterIta),
    cr(0x59BD2000, 0x59BD2FFF, IpClass::DatacenterIta),
    cr(0x59BD3800, 0x59BD3FFF, IpClass::DatacenterIta),
    // ── GOVERNMENT / INSTITUTIONAL ──
    cr(0x5A930000, 0x5A93FFFF, IpClass::GovIta),
    // ── RESIDENTIAL ISPs ──
    cr(0x5B500000, 0x5B5027FF, IpClass::ResidentialIta),
    cr(0x5B502E00, 0x5B502EFF, IpClass::ResidentialIta),
    cr(0x5B503000, 0x5B51FFFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0x5BD64800, 0x5BD64BFF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0x5BE1F400, 0x5BE1F7FF, IpClass::ResidentialIta),
    cr(0x5BE6D900, 0x5BE6D9FF, IpClass::ResidentialIta),
    cr(0x5BFE0000, 0x5BFFFFFF, IpClass::ResidentialIta),
    cr(0x5CDF8000, 0x5CDFFFFF, IpClass::ResidentialIta),
    cr(0x5CF2AC00, 0x5CF2AFFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0x5CF66000, 0x5CF667FF, IpClass::DatacenterIta),
    cr(0x5CF67000, 0x5CF67FFF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0x5D200000, 0x5D47FFFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0x5D586000, 0x5D586FFF, IpClass::DatacenterIta),
    cr(0x5D5D1000, 0x5D5D17FF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0x5D900000, 0x5D97FFFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0x5DBAF000, 0x5DBAFFFF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0x5E200000, 0x5E20FFFF, IpClass::ResidentialIta),
    cr(0x5E220000, 0x5E23FFFF, IpClass::ResidentialIta),
    cr(0x5E500000, 0x5E5C55FF, IpClass::ResidentialIta),
    cr(0x5E5C5700, 0x5E5FFFFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0x5E653000, 0x5E653FFF, IpClass::DatacenterIta),
    cr(0x5E9EB800, 0x5E9EB8FF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0x5EA00000, 0x5EA7FFFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0x5EB1A000, 0x5EB1DFFF, IpClass::DatacenterIta),
    cr(0x5EC66000, 0x5EC665FF, IpClass::DatacenterIta),
    cr(0x5EC66700, 0x5EC667FF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0x5EC70800, 0x5EC70FFF, IpClass::ResidentialIta),
    cr(0x5F4A0000, 0x5F4BFFFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0x5F6E8000, 0x5F6EB3FF, IpClass::DatacenterIta),
    cr(0x5F6EB800, 0x5F6EFFFF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0x5F832800, 0x5F832FFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0x5F8D2000, 0x5F8D2FFF, IpClass::DatacenterIta),
    cr(0x5FA95400, 0x5FA957FF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0x5FE00000, 0x5FFFFFFF, IpClass::ResidentialIta),
    cr(0x65380000, 0x653BFFFF, IpClass::ResidentialIta),
    cr(0x653E0000, 0x653EFFFF, IpClass::ResidentialIta),
    cr(0x6D340000, 0x6D37FFFF, IpClass::ResidentialIta),
    cr(0x6D459000, 0x6D4597FF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0x6D46F000, 0x6D46F7FF, IpClass::DatacenterIta),
    cr(0x6D6B8A00, 0x6D6B8AFF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0x6D700000, 0x6D77FFFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0x6DE85900, 0x6DE859FF, IpClass::DatacenterIta),
    cr(0x6DEA8800, 0x6DEA8FFF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0x80748000, 0x8074FFFF, IpClass::ResidentialIta),
    cr(0x82008000, 0x8200BFFF, IpClass::ResidentialIta),
    cr(0x82190000, 0x8219FFFF, IpClass::ResidentialIta),
    // ── GOVERNMENT / INSTITUTIONAL ──
    cr(0x82880000, 0x8288FFFF, IpClass::GovIta),
    cr(0x82C00000, 0x82C0FFFF, IpClass::GovIta),
    cr(0x82FB0000, 0x82FBFFFF, IpClass::GovIta),
    // ── RESIDENTIAL ISPs ──
    cr(0x83010000, 0x830105FF, IpClass::ResidentialIta),
    cr(0x83010700, 0x830113FF, IpClass::ResidentialIta),
    cr(0x83011500, 0x8301D7FF, IpClass::ResidentialIta),
    cr(0x8301DA00, 0x8301DBFF, IpClass::ResidentialIta),
    cr(0x8301DF00, 0x8301E4FF, IpClass::ResidentialIta),
    cr(0x8301E800, 0x8301EFFF, IpClass::ResidentialIta),
    cr(0x8301F200, 0x8301F2FF, IpClass::ResidentialIta),
    cr(0x8301F600, 0x8301F6FF, IpClass::ResidentialIta),
    cr(0x8301F800, 0x8301FBFF, IpClass::ResidentialIta),
    // ── GOVERNMENT / INSTITUTIONAL ──
    cr(0x83720000, 0x8372FFFF, IpClass::GovIta),
    cr(0x839A0000, 0x839AFFFF, IpClass::GovIta),
    cr(0x83AF0400, 0x83AFBFFF, IpClass::GovIta),
    // ── RESIDENTIAL ISPs ──
    cr(0x86000000, 0x860007FF, IpClass::ResidentialIta),
    // ── GOVERNMENT / INSTITUTIONAL ──
    cr(0x89CC0000, 0x89CCFFFF, IpClass::GovIta),
    cr(0x8A290000, 0x8A29FFFF, IpClass::GovIta),
    cr(0x8C690000, 0x8C69FFFF, IpClass::GovIta),
    cr(0x8CA40000, 0x8CA4FFFF, IpClass::GovIta),
    cr(0x8D6C0000, 0x8D6CFFFF, IpClass::GovIta),
    cr(0x8DFA0000, 0x8DFAFFFF, IpClass::GovIta),
    cr(0x8FE10000, 0x8FE1FFFF, IpClass::GovIta),
    cr(0x92300000, 0x9230FFFF, IpClass::GovIta),
    // ── RESIDENTIAL ISPs ──
    cr(0x92F10000, 0x92F1FFFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0x92FFA000, 0x92FFA7FF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0x93358000, 0x9335FFFF, IpClass::ResidentialIta),
    // ── GOVERNMENT / INSTITUTIONAL ──
    cr(0x937A0000, 0x937AFFFF, IpClass::GovIta),
    cr(0x93A20000, 0x93A3FFFF, IpClass::GovIta),
    // ── DATACENTER / HOSTING ──
    cr(0x93BDD200, 0x93BDD2FF, IpClass::DatacenterIta),
    cr(0x95039000, 0x950397FF, IpClass::DatacenterIta),
    // ── GOVERNMENT / INSTITUTIONAL ──
    cr(0x95840000, 0x9584FFFF, IpClass::GovIta),
    cr(0x958B0000, 0x958BFFFF, IpClass::GovIta),
    cr(0x96910000, 0x9692FFFF, IpClass::GovIta),
    cr(0x96B20000, 0x96B2FFFF, IpClass::GovIta),
    cr(0x96D90000, 0x96D9FFFF, IpClass::GovIta),
    // ── RESIDENTIAL ISPs ──
    cr(0x97008000, 0x9700FFFF, IpClass::ResidentialIta),
    cr(0x97030000, 0x970557FF, IpClass::ResidentialIta),
    cr(0x97056000, 0x970B2FFF, IpClass::ResidentialIta),
    cr(0x970B3600, 0x974FFFFF, IpClass::ResidentialIta),
    cr(0x97510000, 0x9754FFFF, IpClass::ResidentialIta),
    cr(0x975D0000, 0x975DFFFF, IpClass::ResidentialIta),
    cr(0x975F0000, 0x975FFFFF, IpClass::ResidentialIta),
    // ── GOVERNMENT / INSTITUTIONAL ──
    cr(0x97610000, 0x9761FFFF, IpClass::GovIta),
    // ── RESIDENTIAL ISPs ──
    cr(0x97630000, 0x9763C2FF, IpClass::ResidentialIta),
    cr(0x9763C400, 0x9763FFFF, IpClass::ResidentialIta),
    // ── GOVERNMENT / INSTITUTIONAL ──
    cr(0x97640000, 0x9764FFFF, IpClass::GovIta),
    // ── DATACENTER / HOSTING ──
    cr(0x97F80E00, 0x97F80FFF, IpClass::DatacenterIta),
    // ── GOVERNMENT / INSTITUTIONAL ──
    cr(0x9BB90000, 0x9BB9FFFF, IpClass::GovIta),
    cr(0x9BFD0000, 0x9BFDFFFF, IpClass::GovIta),
    cr(0x9C0E0000, 0x9C0EFFFF, IpClass::GovIta),
    // ── RESIDENTIAL ISPs ──
    cr(0x9C364200, 0x9C3642FF, IpClass::ResidentialIta),
    cr(0x9C364800, 0x9C3648FF, IpClass::ResidentialIta),
    cr(0x9C364A00, 0x9C364AFF, IpClass::ResidentialIta),
    cr(0x9C364D00, 0x9C3651FF, IpClass::ResidentialIta),
    cr(0x9C365500, 0x9C3656FF, IpClass::ResidentialIta),
    cr(0x9C365C00, 0x9C3660FF, IpClass::ResidentialIta),
    cr(0x9C367000, 0x9C3673FF, IpClass::ResidentialIta),
    // ── GOVERNMENT / INSTITUTIONAL ──
    cr(0x9C940000, 0x9C94FFFF, IpClass::GovIta),
    cr(0x9D1B0000, 0x9D1BFFFF, IpClass::GovIta),
    // ── DATACENTER / HOSTING ──
    cr(0x9D1C0000, 0x9D1DFFFF, IpClass::DatacenterIta),
    // ── GOVERNMENT / INSTITUTIONAL ──
    cr(0x9D8A0000, 0x9D8AFFFF, IpClass::GovIta),
    // ── DATACENTER / HOSTING ──
    cr(0x9E3AA800, 0x9E3AAFFF, IpClass::DatacenterIta),
    // ── GOVERNMENT / INSTITUTIONAL ──
    cr(0x9E6E0000, 0x9E6EFFFF, IpClass::GovIta),
    // ── RESIDENTIAL ISPs ──
    cr(0x9E940000, 0x9E94FFFF, IpClass::ResidentialIta),
    cr(0x9EFFF000, 0x9EFFF7FF, IpClass::ResidentialIta),
    // ── GOVERNMENT / INSTITUTIONAL ──
    cr(0x9F950000, 0x9F95FFFF, IpClass::GovIta),
    // ── DATACENTER / HOSTING ──
    cr(0x9FFF9C00, 0x9FFF9FFF, IpClass::DatacenterIta),
    // ── GOVERNMENT / INSTITUTIONAL ──
    cr(0xA04E0000, 0xA04EFFFF, IpClass::GovIta),
    cr(0xA0500000, 0xA050FFFF, IpClass::GovIta),
    cr(0xA0610000, 0xA061FFFF, IpClass::GovIta),
    // ── RESIDENTIAL ISPs ──
    cr(0xAAF88800, 0xAAF888FF, IpClass::ResidentialIta),
    cr(0xB03E9800, 0xB03E9FFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0xB06B9000, 0xB06B97FF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0xB07AC400, 0xB07AC6FF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0xB07E6B00, 0xB07E6BFF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0xB0C80000, 0xB0C9FFFF, IpClass::ResidentialIta),
    cr(0xB0CE0000, 0xB0CFFFFF, IpClass::ResidentialIta),
    cr(0xB0F20000, 0xB0F7FFFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0xB2FFF100, 0xB2FFF1FF, IpClass::DatacenterIta),
    cr(0xB9055C00, 0xB9055DFF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0xB9077000, 0xB90773FF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0xB909D000, 0xB909D3FF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0xB90B1400, 0xB90B17FF, IpClass::ResidentialIta),
    cr(0xB9165400, 0xB91655FF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0xB9175400, 0xB91757FF, IpClass::DatacenterIta),
    cr(0xB919CC00, 0xB919CFFF, IpClass::DatacenterIta),
    cr(0xB919E900, 0xB919EBFF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0xB91B4800, 0xB91B4AFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0xB91DF800, 0xB91DFBFF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0xB9244800, 0xB9244BFF, IpClass::ResidentialIta),
    cr(0xB92B1300, 0xB92B13FF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0xB92F8A00, 0xB92F8AFF, IpClass::DatacenterIta),
    cr(0xB9313800, 0xB9313BFF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0xB9362000, 0xB93623FF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0xB936D400, 0xB936D7FF, IpClass::DatacenterIta),
    cr(0xB9380800, 0xB9380BFF, IpClass::DatacenterIta),
    cr(0xB93A7400, 0xB93A77FF, IpClass::DatacenterIta),
    cr(0xB93AC000, 0xB93AC3FF, IpClass::DatacenterIta),
    cr(0xB93B1400, 0xB93B17FF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0xB945BC00, 0xB945BFFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0xB94D5400, 0xB94D57FF, IpClass::DatacenterIta),
    cr(0xB94E3000, 0xB94E33FF, IpClass::DatacenterIta),
    cr(0xB95B4700, 0xB95B47FF, IpClass::DatacenterIta),
    cr(0xB95E5300, 0xB95E53FF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0xB9610C00, 0xB9610CFF, IpClass::ResidentialIta),
    cr(0xB9610E00, 0xB9610EFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0xB961DC00, 0xB961DFFF, IpClass::DatacenterIta),
    cr(0xB9641000, 0xB96411FF, IpClass::DatacenterIta),
    cr(0xB9675000, 0xB96753FF, IpClass::DatacenterIta),
    cr(0xB9687C00, 0xB9687FFF, IpClass::DatacenterIta),
    cr(0xB9695C00, 0xB9695FFF, IpClass::DatacenterIta),
    cr(0xB9696800, 0xB9696BFF, IpClass::DatacenterIta),
    cr(0xB9698000, 0xB96983FF, IpClass::DatacenterIta),
    cr(0xB969D400, 0xB969D7FF, IpClass::DatacenterIta),
    cr(0xB9743C00, 0xB9743CFF, IpClass::DatacenterIta),
    cr(0xB97E8C00, 0xB97E8FFF, IpClass::DatacenterIta),
    cr(0xB98A2400, 0xB98A27FF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0xB98B3000, 0xB98B31FF, IpClass::ResidentialIta),
    cr(0xB9916500, 0xB99165FF, IpClass::ResidentialIta),
    cr(0xB9916700, 0xB99167FF, IpClass::ResidentialIta),
    cr(0xB9928600, 0xB99286FF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0xB99E1C00, 0xB99E1FFF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0xB9A2B300, 0xB9A2B3FF, IpClass::ResidentialIta),
    cr(0xB9A9B800, 0xB9A9BBFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0xB9AB2400, 0xB9AB27FF, IpClass::DatacenterIta),
    cr(0xB9B20C00, 0xB9B20FFF, IpClass::DatacenterIta),
    cr(0xB9BA0C00, 0xB9BA0FFF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0xB9BED600, 0xB9BED7FF, IpClass::ResidentialIta),
    // ── GOVERNMENT / INSTITUTIONAL ──
    cr(0xB9BFB400, 0xB9BFB7FF, IpClass::GovIta),
    // ── DATACENTER / HOSTING ──
    cr(0xB9C30800, 0xB9C30BFF, IpClass::DatacenterIta),
    cr(0xB9C4A400, 0xB9C4A7FF, IpClass::DatacenterIta),
    cr(0xB9C6D200, 0xB9C6D3FF, IpClass::DatacenterIta),
    cr(0xB9CB7C00, 0xB9CB7FFF, IpClass::DatacenterIta),
    cr(0xB9CD2800, 0xB9CD2BFF, IpClass::DatacenterIta),
    cr(0xB9D5DA00, 0xB9D5DBFF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0xB9D7AC00, 0xB9D7AFFF, IpClass::ResidentialIta),
    cr(0xB9D7F000, 0xB9D7F3FF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0xB9D9E400, 0xB9D9E7FF, IpClass::DatacenterIta),
    cr(0xB9DB5500, 0xB9DB55FF, IpClass::DatacenterIta),
    cr(0xB9DB5700, 0xB9DB57FF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0xB9DBB400, 0xB9DBB7FF, IpClass::ResidentialIta),
    cr(0xB9DBE800, 0xB9DBE8FF, IpClass::ResidentialIta),
    cr(0xB9DBEA00, 0xB9DBEAFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0xB9DC3400, 0xB9DC37FF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0xB9DF9900, 0xB9DF99FF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0xB9E5EC00, 0xB9E5EFFF, IpClass::DatacenterIta),
    cr(0xB9F65F00, 0xB9F65FFF, IpClass::DatacenterIta),
    cr(0xB9FAA400, 0xB9FAA7FF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0xBC080000, 0xBC0FFFFF, IpClass::ResidentialIta),
    cr(0xBC980000, 0xBC99FFFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0xBCD5A000, 0xBCD5AFFF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0xBCD80000, 0xBCDBFFFF, IpClass::ResidentialIta),
    cr(0xC0056100, 0xC00561FF, IpClass::ResidentialIta),
    // ── GOVERNMENT / INSTITUTIONAL ──
    cr(0xC029DA00, 0xC029DAFF, IpClass::GovIta),
    cr(0xC0376500, 0xC03765FF, IpClass::GovIta),
    cr(0xC0418300, 0xC04183FF, IpClass::GovIta),
    cr(0xC0547F00, 0xC0549CFF, IpClass::GovIta),
    // ── RESIDENTIAL ISPs ──
    cr(0xC05C7E00, 0xC05C7EFF, IpClass::ResidentialIta),
    cr(0xC05ED400, 0xC05ED4FF, IpClass::ResidentialIta),
    cr(0xC0681700, 0xC06817FF, IpClass::ResidentialIta),
    cr(0xC06A0000, 0xC06ABFFF, IpClass::ResidentialIta),
    cr(0xC06AC100, 0xC06AC3FF, IpClass::ResidentialIta),
    cr(0xC06AC600, 0xC06AE9FF, IpClass::ResidentialIta),
    // ── GOVERNMENT / INSTITUTIONAL ──
    cr(0xC06AEA00, 0xC06AEAFF, IpClass::GovIta),
    // ── RESIDENTIAL ISPs ──
    cr(0xC06AEB00, 0xC06AFFFF, IpClass::ResidentialIta),
    // ── GOVERNMENT / INSTITUTIONAL ──
    cr(0xC06B3300, 0xC06B64FF, IpClass::GovIta),
    cr(0xC0842200, 0xC08422FF, IpClass::GovIta),
    cr(0xC0851C00, 0xC0851CFF, IpClass::GovIta),
    cr(0xC0870800, 0xC08725FF, IpClass::GovIta),
    cr(0xC087A500, 0xC087A5FF, IpClass::GovIta),
    cr(0xC092F200, 0xC092F2FF, IpClass::GovIta),
    cr(0xC094C100, 0xC094C1FF, IpClass::GovIta),
    cr(0xC096C200, 0xC096C4FF, IpClass::GovIta),
    cr(0xC09CD500, 0xC09CD5FF, IpClass::GovIta),
    cr(0xC0A09C00, 0xC0A09CFF, IpClass::GovIta),
    cr(0xC0A70000, 0xC0A7FFFF, IpClass::GovIta),
    // ── RESIDENTIAL ISPs ──
    cr(0xC1033200, 0xC10332FF, IpClass::ResidentialIta),
    cr(0xC11B1C00, 0xC11B1FFF, IpClass::ResidentialIta),
    cr(0xC1230400, 0xC12307FF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0xC12A0200, 0xC12A03FF, IpClass::DatacenterIta),
    cr(0xC12A0E00, 0xC12A0EFF, IpClass::DatacenterIta),
    cr(0xC12A8A00, 0xC12A8AFF, IpClass::DatacenterIta),
    // ── GOVERNMENT / INSTITUTIONAL ──
    cr(0xC12A8B00, 0xC12A8BFF, IpClass::GovIta),
    // ── RESIDENTIAL ISPs ──
    cr(0xC12AEA00, 0xC12AEAFF, IpClass::ResidentialIta),
    cr(0xC12AEE00, 0xC12AEEFF, IpClass::ResidentialIta),
    cr(0xC12B0200, 0xC12B02FF, IpClass::ResidentialIta),
    cr(0xC12B1000, 0xC12B11FF, IpClass::ResidentialIta),
    // ── GOVERNMENT / INSTITUTIONAL ──
    cr(0xC12B1200, 0xC12B13FF, IpClass::GovIta),
    // ── RESIDENTIAL ISPs ──
    cr(0xC12B2C00, 0xC12B2FFF, IpClass::ResidentialIta),
    // ── GOVERNMENT / INSTITUTIONAL ──
    cr(0xC12B6100, 0xC12B61FF, IpClass::GovIta),
    cr(0xC12B6500, 0xC12B65FF, IpClass::GovIta),
    cr(0xC12B6D00, 0xC12B6DFF, IpClass::GovIta),
    cr(0xC12B7400, 0xC12B75FF, IpClass::GovIta),
    cr(0xC12B8D00, 0xC12B8DFF, IpClass::GovIta),
    // ── RESIDENTIAL ISPs ──
    cr(0xC1468000, 0xC14691FF, IpClass::ResidentialIta),
    cr(0xC1469300, 0xC146E1FF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0xC146E200, 0xC146E3FF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0xC146E400, 0xC146FFFF, IpClass::ResidentialIta),
    cr(0xC14C0000, 0xC14CFFFF, IpClass::ResidentialIta),
    cr(0xC1685600, 0xC16856FF, IpClass::ResidentialIta),
    cr(0xC16D5A00, 0xC16D5AFF, IpClass::ResidentialIta),
    cr(0xC16E9700, 0xC16E97FF, IpClass::ResidentialIta),
    cr(0xC18FF900, 0xC18FF9FF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0xC1A48F00, 0xC1A48FFF, IpClass::DatacenterIta),
    cr(0xC1A8D800, 0xC1A8D8FF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0xC1A91400, 0xC1A914FF, IpClass::ResidentialIta),
    cr(0xC1C10000, 0xC1C11FFF, IpClass::ResidentialIta),
    // ── GOVERNMENT / INSTITUTIONAL ──
    cr(0xC1CC0000, 0xC1CEFFFF, IpClass::GovIta),
    // ── RESIDENTIAL ISPs ──
    cr(0xC1CF1800, 0xC1CF1BFF, IpClass::ResidentialIta),
    cr(0xC1CF3000, 0xC1CFFFFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0xC1EE8800, 0xC1EE8BFF, IpClass::DatacenterIta),
    cr(0xC1EFCB00, 0xC1EFCBFF, IpClass::DatacenterIta),
    cr(0xC1F3B800, 0xC1F3B8FF, IpClass::DatacenterIta),
    cr(0xC1FEF000, 0xC1FEF1FF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0xC2059200, 0xC20592FF, IpClass::ResidentialIta),
    cr(0xC2141800, 0xC21418FF, IpClass::ResidentialIta),
    cr(0xC2372C00, 0xC2372FFF, IpClass::ResidentialIta),
    cr(0xC23BD000, 0xC23BD3FF, IpClass::ResidentialIta),
    cr(0xC23F9200, 0xC23F92FF, IpClass::ResidentialIta),
    cr(0xC2632300, 0xC26323FF, IpClass::ResidentialIta),
    // ── GOVERNMENT / INSTITUTIONAL ──
    cr(0xC277C000, 0xC277DFFF, IpClass::GovIta),
    // ── DATACENTER / HOSTING ──
    cr(0xC27E9400, 0xC27E95FF, IpClass::DatacenterIta),
    cr(0xC29C0800, 0xC29C0BFF, IpClass::DatacenterIta),
    cr(0xC2A49100, 0xC2A491FF, IpClass::DatacenterIta),
    cr(0xC2B66E00, 0xC2B66FFF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0xC2B80000, 0xC2B8CCFF, IpClass::ResidentialIta),
    cr(0xC2B8CE00, 0xC2B8FFFF, IpClass::ResidentialIta),
    cr(0xC2F30000, 0xC2F3FFFF, IpClass::ResidentialIta),
    cr(0xC31F0000, 0xC31FFFFF, IpClass::ResidentialIta),
    cr(0xC3204400, 0xC32044FF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0xC327C200, 0xC327C3FF, IpClass::DatacenterIta),
    cr(0xC327CA00, 0xC327CBFF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0xC32D0000, 0xC32DFFFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0xC33CBE00, 0xC33CBFFF, IpClass::DatacenterIta),
    cr(0xC3407400, 0xC34074FF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0xC3670000, 0xC367FFFF, IpClass::ResidentialIta),
    cr(0xC3780000, 0xC378FFFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0xC380EA00, 0xC380EBFF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0xC382E000, 0xC382FFFF, IpClass::ResidentialIta),
    cr(0xC3A25C00, 0xC3A25FFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0xC3B17200, 0xC3B172FF, IpClass::DatacenterIta),
    cr(0xC3BFFB00, 0xC3BFFBFF, IpClass::DatacenterIta),
    cr(0xC3D22100, 0xC3D221FF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0xC3D24000, 0xC3D25FFF, IpClass::ResidentialIta),
    cr(0xC3DF0000, 0xC3DFFFFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0xC3E1A800, 0xC3E1ABFF, IpClass::DatacenterIta),
    cr(0xC3E1E000, 0xC3E1E3FF, IpClass::DatacenterIta),
    cr(0xC3E70000, 0xC3E727FF, IpClass::DatacenterIta),
    cr(0xC3E73000, 0xC3E75FFF, IpClass::DatacenterIta),
    cr(0xC3EAAB00, 0xC3EAABFF, IpClass::DatacenterIta),
    cr(0xC3FA2200, 0xC3FA22FF, IpClass::DatacenterIta),
    cr(0xD1E3E000, 0xD1E3EFFF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0xD40E8000, 0xD40E92FF, IpClass::ResidentialIta),
    cr(0xD40E9400, 0xD40E9FFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0xD411C000, 0xD411DFFF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0xD4344000, 0xD4347FFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0xD436E800, 0xD436FFFF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0xD44E0800, 0xD44E08FF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0xD4736000, 0xD47363FF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0xD47B4000, 0xD47B5FFF, IpClass::ResidentialIta),
    cr(0xD47CA000, 0xD47CBFFF, IpClass::ResidentialIta),
    cr(0xD4830000, 0xD483FFFF, IpClass::ResidentialIta),
    cr(0xD48D0000, 0xD48DFFFF, IpClass::ResidentialIta),
    cr(0xD4AB0000, 0xD4ABFFFF, IpClass::ResidentialIta),
    // ── GOVERNMENT / INSTITUTIONAL ──
    cr(0xD4BD8000, 0xD4BDFFFF, IpClass::GovIta),
    // ── RESIDENTIAL ISPs ──
    cr(0xD4D20000, 0xD4D2FFFF, IpClass::ResidentialIta),
    cr(0xD4D80000, 0xD4D8AFFF, IpClass::ResidentialIta),
    cr(0xD4D8B100, 0xD4D8FFFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0xD4ED0000, 0xD4ED3FFF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0xD4F50000, 0xD4F5FFFF, IpClass::ResidentialIta),
    cr(0xD51A0000, 0xD51AFFFF, IpClass::ResidentialIta),
    cr(0xD52D0000, 0xD52DFFFF, IpClass::ResidentialIta),
    cr(0xD5520000, 0xD552FFFF, IpClass::ResidentialIta),
    cr(0xD56C1F00, 0xD56C1FFF, IpClass::ResidentialIta),
    cr(0xD58C0000, 0xD58C1FFF, IpClass::ResidentialIta),
    cr(0xD59C2000, 0xD59C3FFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0xD5A7E800, 0xD5A7EFFF, IpClass::DatacenterIta),
    cr(0xD5B2C000, 0xD5B2CFFF, IpClass::DatacenterIta),
    cr(0xD5B2D700, 0xD5B2D7FF, IpClass::DatacenterIta),
    cr(0xD5C70000, 0xD5C71FFF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0xD5CD0000, 0xD5CD3FFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0xD5D50000, 0xD5D57FFF, IpClass::DatacenterIta),
    cr(0xD5D98000, 0xD5D9BFFF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0xD5E68000, 0xD5E69FFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0xD5EA8000, 0xD5EABFFF, IpClass::DatacenterIta),
    cr(0xD5FF0000, 0xD5FF7FFF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0xD8F78000, 0xD8F7BFFF, IpClass::ResidentialIta),
    cr(0xD9140400, 0xD9140FFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0xD91C4400, 0xD91C47FF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0xD9380000, 0xD93879FF, IpClass::ResidentialIta),
    cr(0xD9387B00, 0xD9387CFF, IpClass::ResidentialIta),
    cr(0xD9387E00, 0xD93BFFFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0xD93D0800, 0xD93D0FFF, IpClass::DatacenterIta),
    cr(0xD93D1800, 0xD93D3FFF, IpClass::DatacenterIta),
    cr(0xD93D7800, 0xD93D7FFF, IpClass::DatacenterIta),
    cr(0xD9482000, 0xD94827FF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0xD949D000, 0xD949D7FF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0xD949E000, 0xD949EFFF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0xD98D0000, 0xD98DFFFF, IpClass::ResidentialIta),
    cr(0xD9AB4000, 0xD9AB4FFF, IpClass::ResidentialIta),
    cr(0xD9ACC000, 0xD9ACCFFF, IpClass::ResidentialIta),
    cr(0xD9C80000, 0xD9CBFFFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr(0xD9DC0000, 0xD9DDFFFF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr(0xD9DE0000, 0xD9DFFFFF, IpClass::ResidentialIta),
];

/// Sorted by start IP (ascending), non-overlapping.
#[rustfmt::skip]
pub static RANGES6: &[CidrEntry6] = &[
    // ── GOVERNMENT / INSTITUTIONAL ──
    cr6(0x2001067C1B0800000000000000000000, 0x2001067C1B08FFFFFFFFFFFFFFFFFFFF, IpClass::GovIta),
    cr6(0x20010760000000000000000000000000, 0x20010760FFFFFFFFFFFFFFFFFFFFFFFF, IpClass::GovIta),
    // ── RESIDENTIAL ISPs ──
    cr6(0x20010B00000000000000000000000000, 0x20010B07FFFFFFFFFFFFFFFFFFFFFFFF, IpClass::ResidentialIta),
    cr6(0x20014C90000000000000000000000000, 0x20014C97FFFFFFFFFFFFFFFFFFFFFFFF, IpClass::ResidentialIta),
    // ── GOVERNMENT / INSTITUTIONAL ──
    cr6(0x2A001620000000000000000000000000, 0x2A001620FFFFFFFFFFFFFFFFFFFFFFFF, IpClass::GovIta),
    // ── DATACENTER / HOSTING ──
    cr6(0x2A006D40000000000000000000000000, 0x2A006D42FFFFFFFFFFFFFFFFFFFFFFFF, IpClass::DatacenterIta),
    cr6(0x2A006D44000000000000000000000000, 0x2A006D44FFFFFFFFFFFFFFFFFFFFFFFF, IpClass::DatacenterIta),
    cr6(0x2A0082E0000000000000000000000000, 0x2A0082E000FFFFFFFFFFFFFFFFFFFFFF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr6(0x2A0107D0000000000000000000000000, 0x2A0107D0FFFFFFFFFFFFFFFFFFFFFFFF, IpClass::ResidentialIta),
    cr6(0x2A010820000000000000000000000000, 0x2A010820FFFFFFFFFFFFFFFFFFFFFFFF, IpClass::ResidentialIta),
    cr6(0x2A010827000000000000000000000000, 0x2A010827FFFFFFFFFFFFFFFFFFFFFFFF, IpClass::ResidentialIta),
    cr6(0x2A0108D0000000000000000000000000, 0x2A0108D0FFFFFFFFFFFFFFFFFFFFFFFF, IpClass::ResidentialIta),
    cr6(0x2A012000000000000000000000000000, 0x2A012FFFFFFFFFFFFFFFFFFFFFFFFFFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr6(0x2A017540000000000000000000000000, 0x2A017540FFFFFFFFFFFFFFFFFFFFFFFF, IpClass::DatacenterIta),
    cr6(0x2A019A80000000000000000000000000, 0x2A019A83FFFFFFFFFFFFFFFFFFFFFFFF, IpClass::DatacenterIta),
    cr6(0x2A022420000000000000000000000000, 0x2A022420FFFFFFFFFFFFFFFFFFFFFFFF, IpClass::DatacenterIta),
    cr6(0x2A0229E0000100000000000000000000, 0x2A0229E00002FFFFFFFFFFFFFFFFFFFF, IpClass::DatacenterIta),
    cr6(0x2A0229E2000000000000000000000000, 0x2A0229E2FFFFFFFFFFFFFFFFFFFFFFFF, IpClass::DatacenterIta),
    cr6(0x2A024720000000000000000000000000, 0x2A024727FFFFFFFFFFFFFFFFFFFFFFFF, IpClass::DatacenterIta),
    cr6(0x2A024D80000000000000000000000000, 0x2A024D80FFFFFFFFFFFFFFFFFFFFFFFF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr6(0x2A02B000000000000000000000000000, 0x2A02B1FFFFFFFFFFFFFFFFFFFFFFFFFF, IpClass::ResidentialIta),
    cr6(0x2A038980000000000000000000000000, 0x2A038980FFFFFFFFFFFFFFFFFFFFFFFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr6(0x2A03FF80000000000000000000000000, 0x2A03FF87FFFFFFFFFFFFFFFFFFFFFFFF, IpClass::DatacenterIta),
    cr6(0x2A042080000000000000000000000000, 0x2A042087FFFFFFFFFFFFFFFFFFFFFFFF, IpClass::DatacenterIta),
    cr6(0x2A0A5B80000000000000000000000000, 0x2A0A5B87FFFFFFFFFFFFFFFFFFFFFFFF, IpClass::DatacenterIta),
    cr6(0x2A0AE6C0000000000000000000000000, 0x2A0AE6C7FFFFFFFFFFFFFFFFFFFFFFFF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr6(0x2A0BA540000000000000000000000000, 0x2A0BA547FFFFFFFFFFFFFFFFFFFFFFFF, IpClass::ResidentialIta),
    // ── DATACENTER / HOSTING ──
    cr6(0x2A0C79C0000100000000000000000000, 0x2A0C79C00001FFFFFFFFFFFFFFFFFFFF, IpClass::DatacenterIta),
    cr6(0x2A0C79C0000300000000000000000000, 0x2A0C79C00003FFFFFFFFFFFFFFFFFFFF, IpClass::DatacenterIta),
    cr6(0x2A0C79C0000500000000000000000000, 0x2A0C79C00006FFFFFFFFFFFFFFFFFFFF, IpClass::DatacenterIta),
    cr6(0x2A0C79C0000800000000000000000000, 0x2A0C79C00008FFFFFFFFFFFFFFFFFFFF, IpClass::DatacenterIta),
    // ── RESIDENTIAL ISPs ──
    cr6(0x2A0E0400000000000000000000000000, 0x2A0E047FFFFFFFFFFFFFFFFFFFFFFFFF, IpClass::ResidentialIta),
];

/// Const constructor — raw inclusive host-order u32 bounds.
const fn cr(start: u32, end: u32, class: IpClass) -> CidrEntry {
    CidrEntry { start, end, class }
}

/// Const constructor — raw inclusive host-order u128 bounds.
const fn cr6(start: u128, end: u128, class: IpClass) -> CidrEntry6 {
    CidrEntry6 { start, end, class }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ranges_are_sorted() {
        for w in RANGES.windows(2) {
            assert!(w[0].start < w[1].start, "RANGES not sorted");
        }
        for w in RANGES6.windows(2) {
            assert!(w[0].start < w[1].start, "RANGES6 not sorted");
        }
    }

    #[test]
    fn ranges_dont_overlap() {
        for w in RANGES.windows(2) {
            assert!(w[0].end < w[1].start, "RANGES overlap");
        }
        for w in RANGES6.windows(2) {
            assert!(w[0].end < w[1].start, "RANGES6 overlap");
        }
    }
}
