// SPDX-License-Identifier: Apache-2.0
//! Baked-in Italian CIDR ranges for sovereign edge classification.
//!
//! Data sources (all public, verifiable):
//! - RIPE NCC RIS: <https://ris.ripe.net/>
//! - Hurricane Electric BGP Toolkit: <https://bgp.he.net/>
//! - PeeringDB: <https://www.peeringdb.com/>
//! - AgID: <https://www.agid.gov.it/>
//!
//! This file is designed to be regenerated by CI (GitHub Action:
//! `.github/workflows/sovereign-data.yml`) from authoritative sources.
//! Each update is a verifiable PR with a diff of changed ranges.
//!
//! Layout: sorted array of CidrEntry (start, end, class).
//! Binary search in O(log N), zero allocation.
//!
//! Last update: 2026-05-03 (127 ranges across 39 providers).

use super::{cidr_range, CidrEntry, IpClass};

/// Italian CIDR ranges — SORTED by start IP (ascending), non-overlapping.
///
/// INVARIANTS (enforced by tests below):
/// 1. Sorted: `ranges[i].start < ranges[i+1].start` for all i
/// 2. Non-overlapping: `ranges[i].end < ranges[i+1].start` for all i
///
/// 127 ranges covering:
///   - 14 government/institutional (GARR, CNR, INFN, ENEA, Lepida, CINECA, Sapienza)
///   - 97 residential ISP (TIM, Fastweb, Vodafone, WindTre, Iliad, Tiscali,
///     Eolo, Sky WiFi, Brennercom, Linkem, Acantho, Vianova, Panservice, Mynet, Connesi)
///   - 16 datacenter/hosting (Aruba, Seeweb, IRIDEOS, Register.it, Netsons,
///     VHosting, BT Italia, MC-link, Brennercom DC)
pub static RANGES: &[CidrEntry] = &[
    cr(2, 32, 0, 0, 12, IpClass::ResidentialIta), // TIM (AS3269)
    cr(2, 112, 0, 0, 12, IpClass::ResidentialIta), // Vodafone (AS30722)
    cr(2, 192, 0, 0, 14, IpClass::GovIta),        // Fastweb SPC block
    cr(2, 224, 0, 0, 11, IpClass::ResidentialIta), // Fastweb (AS12874)
    cr(5, 63, 136, 0, 21, IpClass::ResidentialIta), // Acantho (AS21309)
    cr(5, 64, 0, 0, 12, IpClass::ResidentialIta), // Fastweb (AS12874)
    cr(5, 88, 0, 0, 15, IpClass::ResidentialIta), // WindTre (AS1267)
    cr(5, 90, 0, 0, 16, IpClass::GovIta),         // GARR academic
    cr(5, 154, 192, 0, 19, IpClass::ResidentialIta), // Connesi (AS15605)
    cr(5, 157, 96, 0, 19, IpClass::ResidentialIta), // Eolo (AS35612)
    cr(5, 168, 0, 0, 13, IpClass::ResidentialIta), // TIM (AS3269)
    cr(5, 199, 128, 0, 17, IpClass::DatacenterIta), // Seeweb (AS49367)
    cr(31, 11, 128, 0, 17, IpClass::GovIta),      // Lepida PA
    cr(31, 44, 160, 0, 20, IpClass::ResidentialIta), // Mynet (AS31263)
    cr(31, 193, 144, 0, 20, IpClass::ResidentialIta), // Mynet (AS31263)
    cr(31, 216, 240, 0, 20, IpClass::ResidentialIta), // Acantho (AS21309)
    cr(37, 0, 0, 0, 13, IpClass::ResidentialIta), // Iliad (AS29447)
    cr(37, 128, 0, 0, 12, IpClass::ResidentialIta), // WindTre (AS1267)
    cr(37, 160, 0, 0, 12, IpClass::ResidentialIta), // TIM (AS3269)
    cr(37, 176, 0, 0, 12, IpClass::ResidentialIta), // Vodafone (AS30722)
    cr(46, 30, 168, 0, 21, IpClass::ResidentialIta), // Connesi (AS15605)
    cr(46, 44, 192, 0, 18, IpClass::ResidentialIta), // Vianova (AS21056)
    cr(46, 234, 224, 0, 19, IpClass::ResidentialIta), // Brennercom (AS20811)
    cr(49, 236, 0, 0, 18, IpClass::ResidentialIta), // Linkem (AS198471)
    cr(62, 77, 32, 0, 20, IpClass::GovIta),       // CINECA
    cr(62, 94, 0, 0, 16, IpClass::DatacenterIta), // IRIDEOS (AS3302)
    cr(62, 149, 0, 0, 16, IpClass::DatacenterIta), // Aruba (AS12797)
    cr(77, 32, 0, 0, 17, IpClass::ResidentialIta), // Eolo (AS35612)
    cr(77, 74, 112, 0, 21, IpClass::ResidentialIta), // Brennercom (AS20811)
    cr(77, 89, 0, 0, 18, IpClass::ResidentialIta), // Acantho (AS21309)
    cr(77, 240, 224, 0, 20, IpClass::ResidentialIta), // Mynet (AS31263)
    cr(77, 241, 0, 0, 21, IpClass::ResidentialIta), // Mynet (AS31263)
    cr(78, 46, 128, 0, 17, IpClass::DatacenterIta), // Register.it (AS31034)
    cr(78, 134, 0, 0, 17, IpClass::ResidentialIta), // Eolo (AS35612)
    cr(78, 152, 96, 0, 19, IpClass::ResidentialIta), // Vianova (AS21056)
    cr(79, 0, 0, 0, 13, IpClass::ResidentialIta), // TIM (AS3269)
    cr(79, 32, 0, 0, 12, IpClass::ResidentialIta), // Fastweb (AS12874)
    cr(79, 56, 0, 0, 13, IpClass::ResidentialIta), // WindTre (AS1267)
    cr(79, 135, 32, 0, 19, IpClass::ResidentialIta), // Vianova (AS21056)
    cr(80, 16, 0, 0, 12, IpClass::ResidentialIta), // TIM (AS3269)
    cr(80, 68, 176, 0, 20, IpClass::ResidentialIta), // Mynet (AS31263)
    cr(80, 86, 144, 0, 20, IpClass::ResidentialIta), // Acantho (AS21309)
    cr(80, 88, 160, 0, 20, IpClass::ResidentialIta), // Mynet (AS31263)
    cr(80, 93, 128, 0, 20, IpClass::ResidentialIta), // Vianova (AS21056)
    cr(80, 180, 0, 0, 14, IpClass::ResidentialIta), // Vodafone (AS30722)
    cr(81, 174, 0, 0, 18, IpClass::ResidentialIta), // Eolo (AS35612)
    cr(82, 48, 0, 0, 12, IpClass::ResidentialIta), // TIM (AS3269)
    cr(83, 137, 56, 0, 21, IpClass::ResidentialIta), // Vianova (AS21056)
    cr(83, 175, 0, 0, 16, IpClass::ResidentialIta), // TIM (AS3269)
    cr(83, 216, 160, 0, 19, IpClass::ResidentialIta), // Acantho (AS21309)
    cr(83, 224, 0, 0, 12, IpClass::ResidentialIta), // Vodafone (AS30722)
    cr(84, 18, 128, 0, 19, IpClass::ResidentialIta), // Brennercom (AS20811)
    cr(84, 33, 64, 0, 18, IpClass::ResidentialIta), // Eolo (AS35612)
    cr(84, 33, 128, 0, 18, IpClass::ResidentialIta), // Eolo (AS35612)
    cr(84, 247, 208, 0, 20, IpClass::ResidentialIta), // Mynet (AS31263)
    cr(84, 247, 224, 0, 19, IpClass::ResidentialIta), // Mynet (AS31263)
    cr(85, 18, 0, 0, 15, IpClass::ResidentialIta), // Fastweb (AS12874)
    cr(86, 110, 128, 0, 19, IpClass::ResidentialIta), // Acantho (AS21309)
    cr(87, 0, 0, 0, 11, IpClass::ResidentialIta), // TIM (AS3269)
    cr(88, 32, 0, 0, 11, IpClass::ResidentialIta), // TIM (AS3269)
    cr(88, 147, 0, 0, 17, IpClass::ResidentialIta), // Eolo (AS35612)
    cr(88, 149, 128, 0, 17, IpClass::ResidentialIta), // Eolo (AS35612)
    cr(89, 31, 72, 0, 21, IpClass::DatacenterIta), // VHosting (AS47541)
    cr(89, 40, 0, 0, 14, IpClass::DatacenterIta), // Aruba Cloud (AS60798)
    cr(89, 46, 0, 0, 15, IpClass::DatacenterIta), // Aruba (AS12797)
    cr(89, 96, 0, 0, 11, IpClass::ResidentialIta), // Tiscali (AS8612)
    cr(89, 190, 160, 0, 19, IpClass::ResidentialIta), // Brennercom (AS20811)
    cr(90, 147, 0, 0, 16, IpClass::GovIta),       // GARR main
    cr(91, 143, 192, 0, 20, IpClass::ResidentialIta), // Vianova (AS21056)
    cr(91, 218, 224, 0, 20, IpClass::DatacenterIta), // Seeweb (AS49367)
    cr(92, 62, 80, 0, 20, IpClass::ResidentialIta), // Mynet (AS31263)
    cr(93, 32, 0, 0, 12, IpClass::ResidentialIta), // TIM (AS3269)
    cr(93, 56, 0, 0, 14, IpClass::ResidentialIta), // Fastweb (AS12874)
    cr(93, 63, 0, 0, 16, IpClass::GovIta),        // GARR secondary
    cr(93, 89, 48, 0, 20, IpClass::ResidentialIta), // Brennercom (AS20811)
    cr(93, 91, 128, 0, 20, IpClass::ResidentialIta), // Mynet (AS31263)
    cr(94, 136, 0, 0, 14, IpClass::DatacenterIta), // Aruba (AS12797)
    cr(95, 171, 32, 0, 19, IpClass::ResidentialIta), // Brennercom (AS20811)
    cr(95, 224, 0, 0, 12, IpClass::ResidentialIta), // TIM (AS3269)
    cr(95, 244, 0, 0, 14, IpClass::ResidentialIta), // Fastweb (AS12874)
    cr(101, 56, 0, 0, 15, IpClass::ResidentialIta), // Sky WiFi (AS210278)
    cr(101, 58, 0, 0, 15, IpClass::ResidentialIta), // Sky WiFi (AS210278)
    cr(101, 62, 0, 0, 16, IpClass::ResidentialIta), // Sky WiFi (AS210278)
    cr(109, 69, 248, 0, 21, IpClass::ResidentialIta), // Brennercom (AS20811)
    cr(109, 73, 80, 0, 20, IpClass::ResidentialIta), // Connesi (AS15605)
    cr(109, 122, 208, 0, 21, IpClass::ResidentialIta), // Vianova (AS21056)
    cr(128, 116, 128, 0, 17, IpClass::ResidentialIta), // Eolo (AS35612)
    cr(146, 241, 0, 0, 16, IpClass::ResidentialIta), // Eolo (AS35612)
    cr(147, 53, 128, 0, 17, IpClass::ResidentialIta), // Eolo (AS35612)
    cr(150, 145, 0, 0, 16, IpClass::GovIta),      // CNR
    cr(151, 0, 0, 0, 13, IpClass::ResidentialIta), // TIM (AS3269)
    cr(151, 32, 0, 0, 12, IpClass::ResidentialIta), // WindTre (AS1267)
    cr(151, 100, 0, 0, 16, IpClass::GovIta),      // Sapienza
    cr(160, 80, 0, 0, 14, IpClass::GovIta),       // GARR university
    cr(176, 40, 0, 0, 13, IpClass::ResidentialIta), // Iliad (AS29447)
    cr(176, 56, 0, 0, 13, IpClass::ResidentialIta), // WindTre (AS1267)
    cr(176, 200, 0, 0, 13, IpClass::ResidentialIta), // TIM (AS3269)
    cr(176, 252, 0, 0, 14, IpClass::ResidentialIta), // Vodafone (AS30722)
    cr(178, 175, 192, 0, 18, IpClass::ResidentialIta), // Mynet (AS31263)
    cr(178, 238, 48, 0, 20, IpClass::ResidentialIta), // Mynet (AS31263)
    cr(185, 6, 192, 0, 22, IpClass::DatacenterIta), // Brennercom DC (AS20811)
    cr(185, 11, 20, 0, 22, IpClass::ResidentialIta), // Eolo (AS35612)
    cr(185, 25, 204, 0, 22, IpClass::DatacenterIta), // Netsons (AS201333)
    cr(185, 36, 140, 0, 22, IpClass::ResidentialIta), // Iliad (AS29447)
    cr(185, 81, 0, 0, 22, IpClass::DatacenterIta), // Netsons (AS201333)
    cr(185, 84, 228, 0, 22, IpClass::ResidentialIta), // Panservice (AS8816)
    cr(185, 111, 144, 0, 22, IpClass::DatacenterIta), // Brennercom DC (AS20811)
    cr(188, 8, 0, 0, 13, IpClass::ResidentialIta), // TIM (AS3269)
    cr(188, 125, 96, 0, 19, IpClass::ResidentialIta), // Acantho (AS21309)
    cr(192, 12, 77, 0, 24, IpClass::GovIta),      // IIT CNR Pisa
    cr(192, 84, 145, 0, 24, IpClass::GovIta),     // ENEA
    cr(192, 106, 144, 0, 21, IpClass::GovIta),    // INFN
    cr(193, 204, 0, 0, 15, IpClass::GovIta),      // GARR backbone
    cr(193, 206, 0, 0, 16, IpClass::GovIta),      // GARR PA network
    cr(195, 110, 0, 0, 17, IpClass::DatacenterIta), // MC-link (AS8928)
    cr(195, 162, 92, 0, 22, IpClass::ResidentialIta), // Sky WiFi (AS210278)
    cr(212, 45, 128, 0, 19, IpClass::ResidentialIta), // Panservice (AS8816)
    cr(212, 121, 64, 0, 19, IpClass::ResidentialIta), // Panservice (AS8816)
    cr(212, 124, 160, 0, 19, IpClass::ResidentialIta), // Eolo (AS35612)
    cr(213, 140, 0, 0, 16, IpClass::DatacenterIta), // BT Italia (AS8968)
    cr(213, 174, 160, 0, 19, IpClass::ResidentialIta), // Acantho (AS21309)
    cr(213, 182, 64, 0, 19, IpClass::ResidentialIta), // Vianova (AS21056)
    cr(213, 209, 192, 0, 18, IpClass::ResidentialIta), // Acantho (AS21309)
    cr(216, 247, 128, 0, 18, IpClass::ResidentialIta), // Eolo (AS35612)
    cr(217, 64, 192, 0, 18, IpClass::DatacenterIta), // Seeweb (AS49367)
    cr(217, 174, 112, 0, 20, IpClass::ResidentialIta), // Panservice (AS8816)
    cr(217, 199, 0, 0, 19, IpClass::ResidentialIta), // Brennercom (AS20811)
];

/// Const constructor for CidrEntry.
const fn cr(a: u8, b: u8, c: u8, d: u8, prefix_len: u8, class: IpClass) -> CidrEntry {
    let (start, end) = cidr_range(a, b, c, d, prefix_len);
    CidrEntry { start, end, class }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ranges_are_sorted() {
        for window in RANGES.windows(2) {
            assert!(
                window[0].start < window[1].start,
                "RANGES not sorted: 0x{:08X} >= 0x{:08X}",
                window[0].start,
                window[1].start
            );
        }
    }

    #[test]
    fn ranges_dont_overlap() {
        for window in RANGES.windows(2) {
            assert!(
                window[0].end < window[1].start,
                "RANGES overlap: [0x{:08X}..0x{:08X}] and [0x{:08X}..0x{:08X}]",
                window[0].start,
                window[0].end,
                window[1].start,
                window[1].end
            );
        }
    }

    #[test]
    fn classify_tim_ip() {
        let ip: std::net::IpAddr = "87.1.2.3".parse().unwrap();
        assert_eq!(super::super::classify(ip), IpClass::ResidentialIta);
    }

    #[test]
    fn classify_garr_ip() {
        let ip: std::net::IpAddr = "90.147.1.1".parse().unwrap();
        assert_eq!(super::super::classify(ip), IpClass::GovIta);
    }

    #[test]
    fn classify_aruba_ip() {
        let ip: std::net::IpAddr = "62.149.1.1".parse().unwrap();
        assert_eq!(super::super::classify(ip), IpClass::DatacenterIta);
    }

    #[test]
    fn classify_eolo_ip() {
        let ip: std::net::IpAddr = "146.241.50.1".parse().unwrap();
        assert_eq!(super::super::classify(ip), IpClass::ResidentialIta);
    }

    #[test]
    fn classify_sky_wifi_ip() {
        let ip: std::net::IpAddr = "101.56.1.1".parse().unwrap();
        assert_eq!(super::super::classify(ip), IpClass::ResidentialIta);
    }

    #[test]
    fn classify_brennercom_ip() {
        let ip: std::net::IpAddr = "46.234.225.1".parse().unwrap();
        assert_eq!(super::super::classify(ip), IpClass::ResidentialIta);
    }

    #[test]
    fn classify_irideos_ip() {
        let ip: std::net::IpAddr = "62.94.1.1".parse().unwrap();
        assert_eq!(super::super::classify(ip), IpClass::DatacenterIta);
    }

    #[test]
    fn classify_acantho_ip() {
        let ip: std::net::IpAddr = "77.89.10.1".parse().unwrap();
        assert_eq!(super::super::classify(ip), IpClass::ResidentialIta);
    }

    #[test]
    fn classify_vianova_ip() {
        let ip: std::net::IpAddr = "46.44.200.1".parse().unwrap();
        assert_eq!(super::super::classify(ip), IpClass::ResidentialIta);
    }

    #[test]
    fn classify_panservice_ip() {
        let ip: std::net::IpAddr = "212.45.130.1".parse().unwrap();
        assert_eq!(super::super::classify(ip), IpClass::ResidentialIta);
    }

    #[test]
    fn classify_mynet_ip() {
        let ip: std::net::IpAddr = "80.88.161.1".parse().unwrap();
        assert_eq!(super::super::classify(ip), IpClass::ResidentialIta);
    }

    #[test]
    fn classify_connesi_ip() {
        let ip: std::net::IpAddr = "109.73.81.1".parse().unwrap();
        assert_eq!(super::super::classify(ip), IpClass::ResidentialIta);
    }

    #[test]
    fn classify_non_italian_ip() {
        let ip: std::net::IpAddr = "8.8.8.8".parse().unwrap();
        assert_eq!(super::super::classify(ip), IpClass::Unknown);
    }

    #[test]
    fn range_count() {
        assert_eq!(RANGES.len(), 127, "Expected 127 ranges in ITA data");
    }
}
