//! ZionDoc → zion.toml (ADR-0011 stage 4).
//!
//! Hand-rolled TOML rendering in the `zion suggest` tradition: no serializer
//! dependency, and the output is gated before it is ever shown — see
//! `self_validate`. The renderer is the only place that writes TOML syntax,
//! so escaping lives here and nowhere else.

use super::map::{RouteOut, UpstreamOut, ZionDoc};

/// Render the document. The result MUST be passed through [`self_validate`]
/// before being emitted anywhere.
pub fn render(doc: &ZionDoc, source: &str) -> String {
    let mut out = String::with_capacity(2048);
    out.push_str(&format!(
        "# Generated by `zion import {source}` — review before deploying.\n"
    ));
    out.push_str("# Findings marked UNSUPPORTED below need a human decision.\n\n");

    out.push_str("[server]\n");
    kv(&mut out, "listen_http", &doc.listen_http);
    kv(&mut out, "listen_https", &doc.listen_https);
    if let Some((rps, window)) = doc.rate_limit {
        out.push_str(&format!("rate_limit_rps = {rps}\n"));
        if window != 1 {
            out.push_str(&format!("rate_limit_window_secs = {window}\n"));
        }
    }
    if let Some(n) = doc.max_conn_per_ip {
        out.push_str(&format!("max_connections_per_ip = {n}\n"));
    }
    if !doc.trusted_proxies.is_empty() {
        out.push_str(&format!(
            "trusted_proxies = [{}]\n",
            doc.trusted_proxies
                .iter()
                .map(|p| toml_str(p))
                .collect::<Vec<_>>()
                .join(", ")
        ));
    }
    out.push('\n');

    out.push_str("[tls]\n");
    kv(&mut out, "cert_path", &doc.tls_cert);
    kv(&mut out, "key_path", &doc.tls_key);
    if doc.tls_min12 {
        kv(&mut out, "min_version", "1.2");
    }
    for sni in &doc.sni {
        out.push_str("\n[[tls.sni]]\n");
        kv(&mut out, "server_name", &sni.server_name);
        kv(&mut out, "cert_path", &sni.cert);
        kv(&mut out, "key_path", &sni.key);
    }
    out.push('\n');

    if let Some(acme) = &doc.acme {
        out.push_str("# Automatic HTTPS via ACME. The cert_path/key_path above are only a\n");
        out.push_str("# bootstrap cert so :443 binds before the first issuance.\n");
        out.push_str("[tls.acme]\n");
        kv(&mut out, "email", &acme.email);
        out.push_str(&format!(
            "domains = [{}]\n",
            acme.domains
                .iter()
                .map(|d| toml_str(d))
                .collect::<Vec<_>>()
                .join(", ")
        ));
        out.push('\n');
    }

    if let Some(mb) = doc.waf_body_mb {
        out.push_str("# Body cap imported from client_max_body_size. Shadow mode logs\n");
        out.push_str("# would-be blocks without enforcing; set waf_shadow = false on the\n");
        out.push_str("# routes below to enforce.\n");
        out.push_str("[waf_profile.imported]\n");
        out.push_str(&format!("max_body_mb = {mb}\n\n"));
    }

    for up in &doc.upstreams {
        render_upstream(&mut out, up);
    }

    for route in &doc.routes {
        render_route(&mut out, route);
    }

    out
}

fn render_upstream(out: &mut String, up: &UpstreamOut) {
    out.push_str(&format!("[upstream.{}]\n", up.name));
    if up.urls.len() == 1 {
        kv(out, "url", &up.urls[0]);
    } else {
        out.push_str(&format!(
            "urls = [{}]\n",
            up.urls
                .iter()
                .map(|u| toml_str(u))
                .collect::<Vec<_>>()
                .join(", ")
        ));
    }
    if let Some(ms) = up.connect_timeout_ms {
        out.push_str(&format!("connect_timeout_ms = {ms}\n"));
    }
    if let Some(k) = up.keepalive {
        out.push_str(&format!("keepalive = {k}\n"));
    }
    out.push('\n');
}

fn render_route(out: &mut String, route: &RouteOut) {
    for note in &route.annotations {
        out.push_str(&format!("# UNSUPPORTED: {}\n", comment_safe(note)));
    }
    out.push_str("[[route]]\n");
    kv(out, "path", &route.path);
    if let Some(hosts) = &route.hosts {
        out.push_str(&format!(
            "hosts = [{}]\n",
            hosts
                .iter()
                .map(|h| toml_str(h))
                .collect::<Vec<_>>()
                .join(", ")
        ));
    }
    if let Some(dir) = &route.serve_dir {
        kv(out, "mode", "static");
        kv(out, "serve_dir", dir);
        if route.spa_fallback {
            out.push_str("spa_fallback = true\n");
        }
    } else {
        kv(out, "upstream", &route.upstream);
        if route.websocket {
            kv(out, "mode", "websocket");
        }
    }
    if let Some(csp) = &route.csp {
        kv(out, "csp", csp);
    }
    if route.waf {
        kv(out, "waf_profile", "imported");
        out.push_str("waf_shadow = true\n");
    }
    out.push('\n');
}

fn kv(out: &mut String, key: &str, value: &str) {
    out.push_str(&format!("{key} = {}\n", toml_str(value)));
}

/// Annotation text is interpolated into `#` comment lines and may carry
/// input-derived content (e.g. a proxy_pass URI part). A newline — legal
/// inside an nginx quoted string — would end the comment and inject raw TOML
/// into the emitted config, so every control character is flattened to a
/// space before rendering.
fn comment_safe(s: &str) -> String {
    s.chars()
        .map(|c| if c.is_control() { ' ' } else { c })
        .collect()
}

/// TOML basic-string escaping: backslash, double quote, and control chars.
fn toml_str(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04X}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// The ADR-0011 gate, mirroring `zion suggest`'s issue-#133 contract and
/// strengthening it: the emitted TOML must (1) round-trip the schema
/// ([`parse_schema`]), (2) pass the filesystem-free semantic checks
/// ([`validate_semantics`]: reference integrity, host validity, URL schemes),
/// and (3) actually build a router. A failure here is an importer bug — the
/// caller must refuse to emit anything.
pub fn self_validate(toml: &str) -> Result<(), String> {
    let cfg = crate::config::parse_schema(toml, "imported config")?;
    crate::config::validate_semantics(&cfg, "imported config")?;
    crate::config::build_router_quiet(&cfg).map_err(|e| format!("router build failed: {e}"))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn annotations_cannot_inject_toml() {
        // A crafted nginx value carrying a newline must not break out of the
        // `# UNSUPPORTED:` comment line (that would inject arbitrary TOML).
        let doc = ZionDoc {
            listen_http: "0.0.0.0:80".into(),
            listen_https: "0.0.0.0:443".into(),
            rate_limit: None,
            max_conn_per_ip: None,
            trusted_proxies: Vec::new(),
            tls_cert: "/c".into(),
            tls_key: "/k".into(),
            tls_min12: false,
            sni: Vec::new(),
            acme: None,
            waf_body_mb: None,
            upstreams: vec![super::super::map::UpstreamOut {
                name: "b".into(),
                urls: vec!["http://127.0.0.1:1".into()],
                connect_timeout_ms: None,
                keepalive: None,
            }],
            routes: vec![super::super::map::RouteOut {
                path: "/{*rest}".into(),
                hosts: None,
                upstream: "b".into(),
                websocket: false,
                csp: None,
                waf: false,
                serve_dir: None,
                spa_fallback: false,
                annotations: vec!["evil\ninternal_only = false\n[admin]".into()],
            }],
        };
        let toml = render(&doc, "nginx");
        assert!(
            !toml.contains("\ninternal_only"),
            "injection broke out of the comment"
        );
        assert!(toml.contains("# UNSUPPORTED: evil internal_only = false [admin]"));
        self_validate(&toml).expect("sanitized output must still validate");
    }

    #[test]
    fn toml_string_escaping() {
        assert_eq!(toml_str("plain"), "\"plain\"");
        assert_eq!(toml_str("a\"b"), "\"a\\\"b\"");
        assert_eq!(toml_str("a\\b"), "\"a\\\\b\"");
        assert_eq!(toml_str("a\nb"), "\"a\\nb\"");
        assert_eq!(toml_str("\u{1}"), "\"\\u0001\"");
    }

    #[test]
    fn minimal_doc_renders_and_validates() {
        let doc = ZionDoc {
            listen_http: "0.0.0.0:80".into(),
            listen_https: "0.0.0.0:443".into(),
            rate_limit: None,
            max_conn_per_ip: None,
            trusted_proxies: Vec::new(),
            tls_cert: "/etc/ssl/zion/zion.crt".into(),
            tls_key: "/etc/ssl/zion/zion.key".into(),
            tls_min12: false,
            sni: Vec::new(),
            acme: None,
            waf_body_mb: None,
            upstreams: vec![super::super::map::UpstreamOut {
                name: "backend".into(),
                urls: vec!["http://127.0.0.1:8080".into()],
                connect_timeout_ms: None,
                keepalive: None,
            }],
            routes: vec![super::super::map::RouteOut {
                path: "/{*rest}".into(),
                hosts: None,
                upstream: "backend".into(),
                websocket: false,
                csp: None,
                waf: false,
                serve_dir: None,
                spa_fallback: false,
                annotations: vec!["demo annotation".into()],
            }],
        };
        let toml = render(&doc, "nginx");
        assert!(toml.contains("# UNSUPPORTED: demo annotation"));
        self_validate(&toml).expect("emitted TOML must self-validate");
    }

    #[test]
    fn full_doc_renders_and_validates() {
        let doc = ZionDoc {
            listen_http: "0.0.0.0:80".into(),
            listen_https: "0.0.0.0:443".into(),
            rate_limit: Some((20, 1)),
            max_conn_per_ip: Some(20),
            trusted_proxies: vec!["173.245.48.0/20".into()],
            tls_cert: "/etc/ssl/a.crt".into(),
            tls_key: "/etc/ssl/a.key".into(),
            tls_min12: true,
            sni: vec![super::super::map::SniOut {
                server_name: "b.example.com".into(),
                cert: "/etc/ssl/b.crt".into(),
                key: "/etc/ssl/b.key".into(),
            }],
            acme: None,
            waf_body_mb: Some(64),
            upstreams: vec![super::super::map::UpstreamOut {
                name: "pool".into(),
                urls: vec!["http://10.0.0.1:80".into(), "http://10.0.0.2:80".into()],
                connect_timeout_ms: Some(75_000),
                keepalive: Some(32),
            }],
            routes: vec![super::super::map::RouteOut {
                path: "/api/{*rest}".into(),
                hosts: Some(vec!["a.example.com".into(), "*.b.example.com".into()]),
                upstream: "pool".into(),
                websocket: true,
                csp: Some("default-src 'self'".into()),
                waf: true,
                serve_dir: None,
                spa_fallback: false,
                annotations: Vec::new(),
            }],
        };
        let toml = render(&doc, "nginx");
        self_validate(&toml).expect("emitted TOML must self-validate");
        assert!(toml.contains("min_version = \"1.2\""));
        assert!(toml.contains("[[tls.sni]]"));
        assert!(toml.contains("waf_profile = \"imported\""));
        assert!(toml.contains("waf_shadow = true"));
        assert!(toml.contains("mode = \"websocket\""));
    }

    #[test]
    fn acme_block_renders_and_validates() {
        let doc = ZionDoc {
            listen_http: "0.0.0.0:80".into(),
            listen_https: "0.0.0.0:443".into(),
            rate_limit: None,
            max_conn_per_ip: None,
            trusted_proxies: Vec::new(),
            tls_cert: "/etc/ssl/zion/zion.crt".into(),
            tls_key: "/etc/ssl/zion/zion.key".into(),
            tls_min12: false,
            sni: Vec::new(),
            acme: Some(super::super::map::AcmeOut {
                email: "ops@example.com".into(),
                domains: vec!["app.example.com".into(), "www.app.example.com".into()],
            }),
            waf_body_mb: None,
            upstreams: vec![super::super::map::UpstreamOut {
                name: "backend".into(),
                urls: vec!["http://127.0.0.1:8080".into()],
                connect_timeout_ms: None,
                keepalive: None,
            }],
            routes: vec![super::super::map::RouteOut {
                path: "/{*rest}".into(),
                hosts: Some(vec!["app.example.com".into()]),
                upstream: "backend".into(),
                websocket: false,
                csp: None,
                waf: false,
                serve_dir: None,
                spa_fallback: false,
                annotations: Vec::new(),
            }],
        };
        let toml = render(&doc, "caddy");
        assert!(toml.contains("[tls.acme]"));
        assert!(toml.contains("email = \"ops@example.com\""));
        assert!(toml.contains("domains = [\"app.example.com\", \"www.app.example.com\"]"));
        // The bootstrap cert must still be present so :443 binds before issuance.
        assert!(toml.contains("cert_path = \"/etc/ssl/zion/zion.crt\""));
        self_validate(&toml).expect("[tls.acme] output must self-validate");
    }
}
