// SPDX-License-Identifier: Apache-2.0
//! `zion suggest` — deterministic `zion.toml` synthesis from detected signals.
//!
//! Phase 1 of issue #133: go from "I have a backend" to "TLS + WAF in front of
//! it" with near-zero hand-editing, and **no ML**. `zion.toml` has a formal
//! schema (the serde structs in [`crate::config`]) and we already own a perfect
//! validator ([`crate::config::parse_schema`] — the serde round-trip), so
//! correctness is guaranteed by the *parser*: this module is strictly
//! **generate → validate → emit**, and never prints a config the parser rejects.
//! (Cert-file existence is a deploy concern, not a schema one — the template
//! carries placeholder cert paths the operator fills in.)
//!
//! Always available (not feature-gated): it's deterministic systems code with
//! zero extra dependencies.

use crate::cli::SuggestOpts;

/// Common localhost dev-server ports, in detection priority order
/// (next/node, vite, django/python, java/generic, flask, phoenix, …).
const DEV_PORTS: &[u16] = &[3000, 5173, 8000, 8080, 5000, 4000, 3001, 8888, 9000, 8001];

/// `zion suggest` entry point. Returns the process exit code.
pub fn run(opts: SuggestOpts) -> i32 {
    // 1. Resolve the upstream: an explicit hint wins, else scan localhost.
    let upstream = match opts.upstream.as_deref() {
        Some(u) => normalize_upstream(u),
        None => match detect_upstream() {
            Some(u) => {
                eprintln!("  detected a listening backend at {u}");
                u
            }
            None => {
                eprintln!("  no local backend detected on common dev ports {DEV_PORTS:?}");
                eprintln!("  hint: pass --upstream <host:port> (e.g. --upstream 127.0.0.1:3000)");
                return 1;
            }
        },
    };
    let domain = opts.domain.as_deref().unwrap_or("localhost");

    // 2. Synthesize, then 3. self-validate — the parser is the guardrail.
    let config = synthesize(&upstream, domain);
    if let Err(e) = crate::config::parse_schema(&config, "suggested config") {
        // A generated config that fails to parse is an internal bug, never the
        // operator's problem — refuse to emit it.
        eprintln!("::error:: internal: generated config failed self-validation: {e}");
        return 1;
    }

    // 4. Emit — to a file (`--write`) or stdout (pipe it yourself).
    match opts.write.as_deref() {
        Some(path) => {
            if let Err(e) = std::fs::write(path, &config) {
                eprintln!("  could not write {path}: {e}");
                return 1;
            }
            eprintln!("  wrote a validated config to {path}");
            eprintln!("  next: set real [tls] cert paths (or `zion init`), then `ZION_CONFIG={path} zion`");
        }
        None => print!("{config}"),
    }
    0
}

/// Normalize an `--upstream` hint to `host:port`. Accepts `:3000`, `3000`,
/// `127.0.0.1:3000`, `api.internal:8080`. A bare port binds to 127.0.0.1.
fn normalize_upstream(hint: &str) -> String {
    let h = hint.trim();
    if let Some(port) = h.strip_prefix(':') {
        return format!("127.0.0.1:{port}");
    }
    if !h.is_empty() && h.bytes().all(|b| b.is_ascii_digit()) {
        return format!("127.0.0.1:{h}");
    }
    h.to_string()
}

/// Probe common localhost dev ports; return the first that accepts a TCP
/// connection. Bounded (100ms/port) so the scan is snappy even when nothing
/// is listening.
fn detect_upstream() -> Option<String> {
    use std::net::TcpStream;
    use std::time::Duration;
    for &port in DEV_PORTS {
        let addr = format!("127.0.0.1:{port}");
        if let Ok(sa) = addr.parse() {
            if TcpStream::connect_timeout(&sa, Duration::from_millis(100)).is_ok() {
                return Some(addr);
            }
        }
    }
    None
}

/// Fill the `zion.toml` skeleton from the signals: TLS + a WAF-protected `/api`
/// route + a catch-all, all pointing at the detected upstream. The operator
/// only needs to set real cert paths. Kept as a plain template (no toml
/// serializer dependency); the output is validated by `config::parse_schema`
/// before it's ever emitted.
fn synthesize(upstream: &str, domain: &str) -> String {
    format!(
        r#"# Generated by `zion suggest` — validated against zion's config schema.
# Set the [tls] cert/key paths below to your real pair (or run `zion init` to
# create a self-signed one), then run:  ZION_CONFIG=zion.toml zion

[server]
listen_http = "0.0.0.0:80"
listen_https = "0.0.0.0:443"

[tls]
# Replace these with your real certificate + key.
cert_path = "/etc/ssl/zion/{domain}.crt"
key_path = "/etc/ssl/zion/{domain}.key"

[upstreams]
backend = "http://{upstream}"

# WAF-protected API; the catch-all forwards everything else to the same backend.
[[route]]
path = "/api/{{*rest}}"
upstream = "backend"
waf = true
max_body_mb = 10

[[route]]
path = "/{{*rest}}"
upstream = "backend"
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn normalize_upstream_forms() {
        assert_eq!(normalize_upstream(":3000"), "127.0.0.1:3000");
        assert_eq!(normalize_upstream("3000"), "127.0.0.1:3000");
        assert_eq!(normalize_upstream("127.0.0.1:8080"), "127.0.0.1:8080");
        assert_eq!(normalize_upstream("api.internal:8080"), "api.internal:8080");
        assert_eq!(normalize_upstream("  :5000  "), "127.0.0.1:5000");
    }

    #[test]
    fn synthesized_config_always_self_validates() {
        // The core contract (#133): every generated config MUST round-trip
        // through the real validator — we never emit one the daemon would
        // reject. Exercise a spread of upstream/domain shapes.
        for (up, dom) in [
            ("127.0.0.1:3000", "localhost"),
            ("api.internal:8080", "api.example.com"),
            ("127.0.0.1:5173", "app.example.com"),
        ] {
            let cfg = synthesize(up, dom);
            let parsed = crate::config::parse_schema(&cfg, "test");
            assert!(
                parsed.is_ok(),
                "synthesized config for {up}/{dom} failed: {:?}",
                parsed.err()
            );
        }
    }

    #[test]
    fn synthesized_config_wires_the_detected_upstream() {
        let cfg = synthesize("127.0.0.1:4000", "localhost");
        assert!(cfg.contains(r#"backend = "http://127.0.0.1:4000""#));
        // WAF on the API route, and the route references the declared upstream.
        assert!(cfg.contains("waf = true"));
        assert!(cfg.contains(r#"upstream = "backend""#));
    }
}
